name: 🚀 Deploy to WordPress via SFTP

on:
  push:
    branches:
      - main  # Change to 'master' if you're using that

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to cPanel via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /public_html/wp-content/plugins/vpn-profile-manager/
