name: 🚀 Deploy to WordPress via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_HOST }}           # e.g. ebmohsen.com or IP
          username: ${{ secrets.FTP_USER }}       # e.g. githubmohsen@ebmohsen.com
          password: ${{ secrets.FTP_PASS }}       # your FTP password
          port: 22                                # <--- This is key for SFTP
          source: "./"
          target: "/home/YOURCPANELUSER/public_html/wp-content/plugins/vpn-profile-manager"
